{% set data = load_setup_py_data(from_recipe_dir=True) %}
{% set name = data['name'] %}
{% set version = data['version'] %}
{% set summary = data['description'] %}
{% set description = data['long_description'][:data['long_description'].index('<table>')].strip() %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 679887fc30d0331457c275ebd46d2bdd9f87424c33dddf4a467046d64c1aeef7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ data['python_requires'] }}
    - pip
    - setuptools
  run:
    - python {{ data['python_requires'] }}
{% for dep in data['install_requires'] %}
{% if dep.lower().startswith('matplotlib') %}
    - matplotlib-base
{% else %}
    - {{ dep.lower() }}
{% endif %}
{% endfor %}

test:
  imports:
    - {{ name.lower() }}
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  license_file: {{ data['license_files'][0] }}
  summary: {{ summary }}
  description: {{ description }}
  doc_url: https://{{ name.lower() }}.readthedocs.io/
  doc_source_url: {{ data['url'] }}/blob/master/docs/source/index.rst
  dev_url: {{ data['url'] }}

extra:
  maintainers:
   - TommasoBelluzzo
