{% set data = load_setup_py_data(from_recipe_dir=True) %}
{% set name = data['name'] %}
{% set version = data['version'] %}
{% set summary = data['description'] %}
{% set description = data['long_description'][:data['long_description'].index('<table>')].strip() %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: sha256_placeholder

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ data['python_requires'] }}
    - pip
  build:
    - python {{ data['python_requires'] }}
    - pip
    - setuptools
  run:
    - python {{ data['python_requires'] }}
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - {{ name.lower() }}
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  license_file: {{ data['license_files'] }}
  summary: {{ summary }}
  description: {{ description }}
  dev_url: {{ data['url'] }}
  doc_url: https://{{ name.lower() }}.readthedocs.io/
  doc_source_url: {{ data['url'] }}/blob/master/README.md

extra:
  maintainers:
   - TommasoBelluzzo