name: "Code Analysis"

on:
  schedule:
    - cron: '00 19 1 * *'

jobs:
  code_analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
    - name: Analysis Initialization
      uses: github/codeql-action/init@v2
      with:
        languages: python
    - name: Analysis Execution
      uses: github/codeql-action/analyze@v2
