name: "Code Analysis"

on:
  schedule:
    - cron: '00 19 1 * *'

jobs:
  task:
    name: Task
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: Analysis Initialization
      uses: github/codeql-action/init@v1
      with:
        languages: python
    - name: Analysis Execution
      uses: github/codeql-action/analyze@v1
