name: "Package Publishing TEST"

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Target:'
        required: true
        options:
        - MAJOR
        - MINOR
        - RELEASE
        - NONE
        default: 'MINOR'
      pypi:
        type: boolean
        description: 'PyPI:'
        required: true
        default: true
      conda:
        type: boolean
        description: 'Conda:'
        required: true
        default: true

jobs:
  package_publishing_test:
    name: Package Publishing TEST
    runs-on: ubuntu-latest
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Version Bump
      id: bump
      env:
        TARGET: ${{ github.event.inputs.target }}
        PYPI: ${{ github.event.inputs.pypi }}
        CONDA: ${{ github.event.inputs.conda }}
        VERSION_REGEX: __version__ = '\d+\.\d+\.\d+'
        VERSION_FILE: pydtmc/__init__.py
      run: |
        TARGET="${TARGET^^}"
        echo $TARGET
        PYPI="${PYPI^^}"
        echo $PYPI
        CONDA="${CONDA^^}"
        echo $CONDA
